# Autogenerated from SVG specification. Edits may be lost.

svgelement = [
    (str, 'class_name', 'className'),
    (str, 'style', 'style'),
    (str, 'ownersvg_element', 'ownerSVGElement'),
    (str, 'viewport_element', 'viewportElement'),
    (int, 'tab_index', 'tabIndex')
]

svgelementcollection = []

mpath = [
    (str, 'href', 'href')
]

mpathcollection = []

animation = [
    (str, 'target_element', 'targetElement'),
    (str, 'onbegin', 'onbegin'),
    (str, 'onend', 'onend'),
    (str, 'onrepeat', 'onrepeat'),
    (str, 'required_features', 'requiredFeatures'),
    (str, 'required_extensions', 'requiredExtensions'),
    (str, 'system_language', 'systemLanguage')
]

animationcollection = []

animatetransform = []

animatetransformcollection = []

animatemotion = []

animatemotioncollection = []

set = []

setcollection = []

animate = []

animatecollection = []

view = [
    (str, 'view_target', 'viewTarget'),
    (str, 'view_box', 'viewBox'),
    (str, 'preserve_aspect_ratio', 'preserveAspectRatio'),
    (int, 'zoom_and_pan', 'zoomAndPan')
]

viewcollection = []

cursor = [
    (int, 'x', 'x'),
    (int, 'y', 'y'),
    (str, 'href', 'href')
]

cursorcollection = []

pattern = [
    (str, 'pattern_units', 'patternUnits'),
    (str, 'pattern_content_units', 'patternContentUnits'),
    (str, 'pattern_transform', 'patternTransform'),
    (int, 'x', 'x'),
    (int, 'y', 'y'),
    (int, 'width', 'width'),
    (int, 'height', 'height'),
    (str, 'view_box', 'viewBox'),
    (str, 'preserve_aspect_ratio', 'preserveAspectRatio'),
    (str, 'href', 'href')
]

patterncollection = []

stop = [
    (str, 'offset', 'offset')
]

stopcollection = []

meshpatch = []

meshpatchcollection = []

meshrow = []

meshrowcollection = []

gradient = [
    (str, 'gradient_units', 'gradientUnits'),
    (str, 'gradient_transform', 'gradientTransform'),
    (str, 'spread_method', 'spreadMethod'),
    (str, 'href', 'href')
]

gradientcollection = []

meshgradient = [
    (int, 'x', 'x'),
    (int, 'y', 'y')
]

meshgradientcollection = []

radialgradient = [
    (int, 'cx', 'cx'),
    (int, 'cy', 'cy'),
    (int, 'r', 'r'),
    (int, 'fx', 'fx'),
    (int, 'fy', 'fy'),
    (int, 'fr', 'fr')
]

radialgradientcollection = []

lineargradient = [
    (int, 'x1', 'x1'),
    (int, 'y1', 'y1'),
    (int, 'x2', 'x2'),
    (int, 'y2', 'y2')
]

lineargradientcollection = []

marker = [
    (int, 'refx', 'refX'),
    (int, 'refy', 'refY'),
    (str, 'marker_units', 'markerUnits'),
    (int, 'marker_width', 'markerWidth'),
    (int, 'marker_height', 'markerHeight'),
    (str, 'orient_type', 'orientType'),
    (str, 'orient_angle', 'orientAngle'),
    (str, 'orient', 'orient'),
    (str, 'view_box', 'viewBox'),
    (str, 'preserve_aspect_ratio', 'preserveAspectRatio')
]

markercollection = []

symbol = [
    (str, 'view_box', 'viewBox'),
    (str, 'preserve_aspect_ratio', 'preserveAspectRatio')
]

symbolcollection = []

metadata = []

metadatacollection = []

desc = []

desccollection = []

graphics = [
    (str, 'transform', 'transform'),
    (str, 'required_features', 'requiredFeatures'),
    (str, 'required_extensions', 'requiredExtensions'),
    (str, 'system_language', 'systemLanguage')
]

graphicscollection = []

foreignobject = [
    (int, 'x', 'x'),
    (int, 'y', 'y'),
    (int, 'width', 'width'),
    (int, 'height', 'height')
]

foreignobjectcollection = []

textcontent = [
    (int, 'text_length', 'textLength'),
    (str, 'length_adjust', 'lengthAdjust')
]

textcontentcollection = []

textpath = [
    (int, 'start_offset', 'startOffset'),
    (str, 'method', 'method'),
    (str, 'spacing', 'spacing'),
    (str, 'href', 'href'),
    (str, 'path_seg_list', 'pathSegList'),
    (str, 'animated_path_seg_list', 'animatedPathSegList')
]

textpathcollection = []

textpositioning = [
    (str, 'x', 'x'),
    (str, 'y', 'y'),
    (str, 'dx', 'dx'),
    (str, 'dy', 'dy'),
    (str, 'rotate', 'rotate')
]

textpositioningcollection = []

tspan = []

tspancollection = []

switch = []

switchcollection = []

use = [
    (int, 'x', 'x'),
    (int, 'y', 'y'),
    (int, 'width', 'width'),
    (int, 'height', 'height'),
    (str, 'href', 'href')
]

usecollection = []

defs = []

defscollection = []

g = []

gcollection = []

svg = [
    (int, 'x', 'x'),
    (int, 'y', 'y'),
    (int, 'width', 'width'),
    (int, 'height', 'height'),
    (str, 'viewport', 'viewport'),
    (bool, 'use_current_view', 'useCurrentView'),
    (str, 'current_view', 'currentView'),
    (float, 'current_scale', 'currentScale'),
    (str, 'current_translate', 'currentTranslate'),
    (str, 'view_box', 'viewBox'),
    (str, 'preserve_aspect_ratio', 'preserveAspectRatio'),
    (int, 'zoom_and_pan', 'zoomAndPan')
]

svgcollection = []

geometry = []

geometrycollection = []

polygon = [
    (str, 'points', 'points'),
    (str, 'animated_points', 'animatedPoints')
]

polygoncollection = []

polyline = [
    (str, 'points', 'points'),
    (str, 'animated_points', 'animatedPoints')
]

polylinecollection = []

line = [
    (int, 'x1', 'x1'),
    (int, 'y1', 'y1'),
    (int, 'x2', 'x2'),
    (int, 'y2', 'y2')
]

linecollection = []

ellipse = [
    (int, 'cx', 'cx'),
    (int, 'cy', 'cy'),
    (int, 'rx', 'rx'),
    (int, 'ry', 'ry')
]

ellipsecollection = []

circle = [
    (int, 'cx', 'cx'),
    (int, 'cy', 'cy'),
    (int, 'r', 'r')
]

circlecollection = []

rect = [
    (int, 'x', 'x'),
    (int, 'y', 'y'),
    (int, 'width', 'width'),
    (int, 'height', 'height'),
    (int, 'rx', 'rx'),
    (int, 'ry', 'ry')
]

rectcollection = []

path = [
    (str, 'path_length', 'pathLength'),
    (str, 'path_seg_list', 'pathSegList'),
    (str, 'animated_path_seg_list', 'animatedPathSegList')
]

pathcollection = []

