from .area import Area
from .button import Button
from .cell import Cell
from .checkbox import CheckBox
from .dlist import DList
from .element import Element
from .file_field import FileField
from .form import Form
from .hidden import Hidden
from .html_elements import HTMLElement
from .iframe import Frame, IFrame
from .image import Image
from .input import Input
from .link import Anchor
from .option import Option
from .radio import Radio
from .row import Row
from .select import Select
from .svg_elements import SVGElement
from .table import Table
from .table_cell import TableCell
from .table_row import TableRow
from .table_section import TableSection
from .text_area import TextArea
from .text_field import TextField
from .html_elements import HTMLElementCollection
from .html_elements import Font
from .html_elements import FontCollection
from .html_elements import Directory
from .html_elements import DirectoryCollection
from .html_elements import FrameSet
from .html_elements import FrameSetCollection
from .html_elements import Marquee
from .html_elements import MarqueeCollection
from .html_elements import Applet
from .html_elements import AppletCollection
from .html_elements import Canvas
from .html_elements import CanvasCollection
from .html_elements import Template
from .html_elements import TemplateCollection
from .html_elements import Script
from .html_elements import ScriptCollection
from .html_elements import Dialog
from .html_elements import DialogCollection
from .html_elements import MenuItem
from .html_elements import MenuItemCollection
from .html_elements import Menu
from .html_elements import MenuCollection
from .html_elements import Details
from .html_elements import DetailsCollection
from .html_elements import Legend
from .html_elements import LegendCollection
from .html_elements import FieldSet
from .html_elements import FieldSetCollection
from .html_elements import Meter
from .html_elements import MeterCollection
from .html_elements import Progress
from .html_elements import ProgressCollection
from .html_elements import Output
from .html_elements import OutputCollection
from .html_elements import Keygen
from .html_elements import KeygenCollection
from .html_elements import TextAreaCollection
from .html_elements import OptionCollection
from .html_elements import OptGroup
from .html_elements import OptGroupCollection
from .html_elements import DataList
from .html_elements import DataListCollection
from .html_elements import SelectCollection
from .html_elements import ButtonCollection
from .html_elements import InputCollection
from .html_elements import Label
from .html_elements import LabelCollection
from .html_elements import FormCollection
from .html_elements import TableCellCollection
from .html_elements import TableHeaderCell
from .html_elements import TableHeaderCellCollection
from .html_elements import TableDataCell
from .html_elements import TableDataCellCollection
from .html_elements import TableRowCollection
from .html_elements import TableSectionCollection
from .html_elements import TableCol
from .html_elements import TableColCollection
from .html_elements import TableCaption
from .html_elements import TableCaptionCollection
from .html_elements import TableCollection
from .html_elements import AreaCollection
from .html_elements import Map
from .html_elements import MapCollection
from .html_elements import Media
from .html_elements import MediaCollection
from .html_elements import Audio
from .html_elements import AudioCollection
from .html_elements import Video
from .html_elements import VideoCollection
from .html_elements import Track
from .html_elements import TrackCollection
from .html_elements import Param
from .html_elements import ParamCollection
from .html_elements import Object
from .html_elements import ObjectCollection
from .html_elements import Embed
from .html_elements import EmbedCollection
from .html_elements import IFrameCollection
from .html_elements import ImageCollection
from .html_elements import Source
from .html_elements import SourceCollection
from .html_elements import Picture
from .html_elements import PictureCollection
from .html_elements import Mod
from .html_elements import ModCollection
from .html_elements import BR
from .html_elements import BRCollection
from .html_elements import Span
from .html_elements import SpanCollection
from .html_elements import Time
from .html_elements import TimeCollection
from .html_elements import Data
from .html_elements import DataCollection
from .html_elements import AnchorCollection
from .html_elements import Div
from .html_elements import DivCollection
from .html_elements import DListCollection
from .html_elements import LI
from .html_elements import LICollection
from .html_elements import UList
from .html_elements import UListCollection
from .html_elements import OList
from .html_elements import OListCollection
from .html_elements import Quote
from .html_elements import QuoteCollection
from .html_elements import Pre
from .html_elements import PreCollection
from .html_elements import HR
from .html_elements import HRCollection
from .html_elements import Paragraph
from .html_elements import ParagraphCollection
from .html_elements import Heading
from .html_elements import HeadingCollection
from .html_elements import Body
from .html_elements import BodyCollection
from .html_elements import Style
from .html_elements import StyleCollection
from .html_elements import Meta
from .html_elements import MetaCollection
from .html_elements import Base
from .html_elements import BaseCollection
from .html_elements import Title
from .html_elements import TitleCollection
from .html_elements import Head
from .html_elements import HeadCollection
from .html_elements import Html
from .html_elements import HtmlCollection
from .html_elements import Unknown
from .html_elements import UnknownCollection
from .svg_elements import SVGElementCollection
from .svg_elements import MPath
from .svg_elements import MPathCollection
from .svg_elements import Animation
from .svg_elements import AnimationCollection
from .svg_elements import AnimateTransform
from .svg_elements import AnimateTransformCollection
from .svg_elements import AnimateMotion
from .svg_elements import AnimateMotionCollection
from .svg_elements import Set
from .svg_elements import SetCollection
from .svg_elements import Animate
from .svg_elements import AnimateCollection
from .svg_elements import View
from .svg_elements import ViewCollection
from .svg_elements import Cursor
from .svg_elements import CursorCollection
from .svg_elements import Pattern
from .svg_elements import PatternCollection
from .svg_elements import Stop
from .svg_elements import StopCollection
from .svg_elements import MeshPatch
from .svg_elements import MeshPatchCollection
from .svg_elements import MeshRow
from .svg_elements import MeshRowCollection
from .svg_elements import Gradient
from .svg_elements import GradientCollection
from .svg_elements import MeshGradient
from .svg_elements import MeshGradientCollection
from .svg_elements import RadialGradient
from .svg_elements import RadialGradientCollection
from .svg_elements import LinearGradient
from .svg_elements import LinearGradientCollection
from .svg_elements import Marker
from .svg_elements import MarkerCollection
from .svg_elements import Symbol
from .svg_elements import SymbolCollection
from .svg_elements import Metadata
from .svg_elements import MetadataCollection
from .svg_elements import Desc
from .svg_elements import DescCollection
from .svg_elements import Graphics
from .svg_elements import GraphicsCollection
from .svg_elements import ForeignObject
from .svg_elements import ForeignObjectCollection
from .svg_elements import TextContent
from .svg_elements import TextContentCollection
from .svg_elements import TextPath
from .svg_elements import TextPathCollection
from .svg_elements import TextPositioning
from .svg_elements import TextPositioningCollection
from .svg_elements import TSpan
from .svg_elements import TSpanCollection
from .svg_elements import Switch
from .svg_elements import SwitchCollection
from .svg_elements import Use
from .svg_elements import UseCollection
from .svg_elements import Defs
from .svg_elements import DefsCollection
from .svg_elements import G
from .svg_elements import GCollection
from .svg_elements import SVG
from .svg_elements import SVGCollection
from .svg_elements import Geometry
from .svg_elements import GeometryCollection
from .svg_elements import Polygon
from .svg_elements import PolygonCollection
from .svg_elements import Polyline
from .svg_elements import PolylineCollection
from .svg_elements import Line
from .svg_elements import LineCollection
from .svg_elements import Ellipse
from .svg_elements import EllipseCollection
from .svg_elements import Circle
from .svg_elements import CircleCollection
from .svg_elements import Rect
from .svg_elements import RectCollection
from .svg_elements import Path
from .svg_elements import PathCollection
